### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by patatetom** [mborgerson/fatx#5] opened 2017-12-04 17:01 UTC
hello,
compilation is meeting errors under Linux :
```
$ make      
[  8%] Building C object CMakeFiles/libfatxfs.dir/src/fatx.c.o
[ 16%] Building C object CMakeFiles/libfatxfs.dir/src/fatx_attr.c.o
[ 25%] Building C object CMakeFiles/libfatxfs.dir/src/fatx_dev.c.o
[ 33%] Building C object CMakeFiles/libfatxfs.dir/src/fatx_dir.c.o
[ 41%] Building C object CMakeFiles/libfatxfs.dir/src/fatx_fat.c.o
[ 50%] Building C object CMakeFiles/libfatxfs.dir/src/fatx_file.c.o
[ 58%] Building C object CMakeFiles/libfatxfs.dir/src/fatx_log.c.o
[ 66%] Building C object CMakeFiles/libfatxfs.dir/src/fatx_misc.c.o
[ 75%] Building C object CMakeFiles/libfatxfs.dir/src/fatx_partition.c.o
[ 83%] Linking C static library liblibfatxfs.a
[ 83%] Built target libfatxfs
[ 91%] Building C object CMakeFiles/fatxfs.dir/src/fatxfs_fuse.c.o
In file included from /tmp/fatx-master/src/fatxfs_fuse.c:31:0:
/usr/include/fuse/fuse.h:444:54: error: array type has incomplete element type 'struct timespec'
  int (*utimens) (const char *, const struct timespec tv[2]);
                                                      ^~
/usr/include/fuse/fuse.h:444:45: warning: 'struct timespec' declared inside parameter list will not be visible outside of this definition or declaration
  int (*utimens) (const char *, const struct timespec tv[2]);
                                             ^~~~~~~~
/usr/include/fuse/fuse.h:867:29: error: array type has incomplete element type 'struct timespec'
       const struct timespec tv[2]);
                             ^~
/usr/include/fuse/fuse.h:867:20: warning: 'struct timespec' declared inside parameter list will not be visible outside of this definition or declaration
       const struct timespec tv[2]);
                    ^~~~~~~~
make[2]: *** [CMakeFiles/fatxfs.dir/build.make:63: CMakeFiles/fatxfs.dir/src/fatxfs_fuse.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/fatxfs.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
regards.

**Comment by mborgerson** [comment] 2017-12-04 21:30
Thanks for the filing!

Duplicate of #3

**Closed by mborgerson** 2017-12-04 21:30 UTC

**Comment by patatetom** [comment] 2018-01-05 09:34
hello Matt and happy new year,
do you plan to make a patch for fatxfs available soon ?
regards, lacsaP.
